version: '3.3'

services:
  books-wagon-web:
    image: books-wagon:latest
    build: .
    container_name: books-wagon-web
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - books-wagon

networks:
 books-wagon:
   driver: bridge

